name: flutter_geogame
description: A Geocaching Party Game.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  mapbox_gl: ^0.0.3
  location: ^2.3.5
  firebase_core: ^0.4.0+9
  cloud_firestore: ^0.12.9+4
  equatable: ^0.5.0
  rxdart: ^0.22.0 # optional
  flutter_bloc: ^0.21.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
